# Generated by Django 4.2.30 on 2026-05-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.IntegerField(default=0, verbose_name="积分余额"),
        ),
    ]
