# Generated by Django 4.2.30 on 2026-05-18 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="优惠券编码"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="优惠券名称")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "百分比折扣"), ("fixed", "固定金额减免")],
                        max_length=10,
                        verbose_name="折扣类型",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="折扣值"
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="最低消费金额",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="生效时间")),
                ("valid_to", models.DateTimeField(verbose_name="失效时间")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "total_count",
                    models.IntegerField(default=0, verbose_name="发行总量"),
                ),
                (
                    "used_count",
                    models.IntegerField(default=0, verbose_name="已使用数量"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "优惠券",
                "verbose_name_plural": "优惠券",
                "db_table": "coupons",
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unused", "未使用"),
                            ("used", "已使用"),
                            ("expired", "已过期"),
                        ],
                        default="unused",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="领取时间"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to="coupon.coupon",
                        verbose_name="优惠券",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户优惠券",
                "verbose_name_plural": "用户优惠券",
                "db_table": "user_coupons",
            },
        ),
        migrations.CreateModel(
            name="PointsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(verbose_name="积分变动（正为获取，负为消费）"),
                ),
                ("balance", models.IntegerField(verbose_name="变动后余额")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("register", "注册赠送"),
                            ("purchase", "购买获赠"),
                            ("redeem", "抵扣使用"),
                            ("refund", "退款退回"),
                            ("expire", "积分过期"),
                        ],
                        max_length=20,
                        verbose_name="变动类型",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order.order",
                        verbose_name="关联订单",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "积分流水",
                "verbose_name_plural": "积分流水",
                "db_table": "points_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
