# Generated by Django 4.2.30 on 2026-05-14 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序权重")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="courses.category",
                        verbose_name="父分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程分类",
                "verbose_name_plural": "课程分类",
                "db_table": "course_categories",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="章节标题")),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="章节简介"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "章节",
                "verbose_name_plural": "章节",
                "db_table": "course_chapters",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="课时标题")),
                (
                    "video_url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="视频地址"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(default=0, verbose_name="视频时长（秒）"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_preview",
                    models.BooleanField(default=False, verbose_name="是否可试看"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.chapter",
                        verbose_name="所属章节",
                    ),
                ),
            ],
            options={
                "verbose_name": "课时",
                "verbose_name_plural": "课时",
                "db_table": "course_lessons",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="课程标题")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="副标题"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="课程详情"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        default="",
                        upload_to="covers/%Y/%m/",
                        verbose_name="封面图",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="当前售价",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="原价",
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(default=False, verbose_name="是否免费"),
                ),
                (
                    "points_required",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="积分兑换所需分数"
                    ),
                ),
                (
                    "coupon_config",
                    models.JSONField(
                        blank=True, null=True, verbose_name="优惠规则配置"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="课程状态",
                    ),
                ),
                (
                    "learn_count",
                    models.IntegerField(default=0, verbose_name="学习人数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="courses.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taught_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="授课教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "db_table": "courses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="courses.course",
                verbose_name="所属课程",
            ),
        ),
    ]
