# Generated by Django 4.2.30 on 2026-05-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="课程详情"
            ),
        ),
    ]
