# Generated by Django 4.2.30 on 2026-05-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="优惠券减免"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="final_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="实付金额"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="points_discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="积分抵扣金额"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="points_used",
            field=models.IntegerField(default=0, verbose_name="使用的积分"),
        ),
        migrations.AddField(
            model_name="order",
            name="user_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coupon.usercoupon",
                verbose_name="使用的优惠券",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="原订单金额"
            ),
        ),
    ]
